### ISSUE TITLE
HTTP Proxy support

### ISSUE THREAD

**Issue by michag86** [m-lab/ndt7-client-go#95]
Can I use ndt7-prometheus-exporter behind a http proxy?
I tried it with setting the environment https_proxy, http_proxy, HTTPS_PROXY and HTTP_PROXY but nothing worked:

My docker-compose.yml looks like this:
```
version: "3"

services:
  ndt-exporter:
    image: ndt7-prometheus-exporter
    ports:
      - 9191:8080
    environment:
      http_proxy: http://myproxy.com:3128
      https_proxy: http://myproxy.com:3128
      HTTP_PROXY: http://myproxy.com:3128
      HTTPS_PROXY: http://myproxy.com:3128
    command:
      - -timeout
      - 3s
      - -server
      - ndt.mydomain.com
 ```

It always looks like it trys to connect directly:
 ```
download failed: dial tcp 123.x.x.x:443: i/o timeout
upload failed: dial tcp: lookup ndt.mydomain.com: i/o timeout
 ```
